load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
    name = "25",
    srcs = ["Day25.cpp"],
    data = [
        "input_day25.txt",
        "input_day25_test.txt",
    ],
    deps = [
        "//2017/lib",
    ],
)
